import json
from pathlib import Path
from typing import List, Dict, Tuple, Union

from ScopeFoundry.generate_loaders_py import generate_loaders_py, get_measurement_name,\
    get_dset_names
from .helper_funcs import open_file


IPYNB_DEMO_FNAME = "overview.ipynb"


def new_empty_nb_content(n_cells: int = 2) -> Dict:
    """returns the content of ipynb with n_cell empty cells"""
    return {
        "cells": [
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [],
            }
            for _ in range(n_cells)
        ],
        "metadata": {},
    }


def get_dset_names(fname: Path) -> List[str]:
    import h5py

    dset_names = []

    def visitor(name, node):
        if isinstance(node, h5py.Dataset):
            dset_names.append(node.name.split("/")[-1])

    try:
        with h5py.File(fname, "r") as file:
            file.visititems(visitor)
    except Exception as e:
        print(f"failed to read {fname}: {e}")

    return dset_names


def get_files_metadata(
    folder: str, nb_content: Dict
) -> Dict[str, Dict[str, Union[str, bool, List[str]]]]:
    path = Path(folder)
    files_metadata = nb_content["metadata"].get("files_metadata", {})
    for fname in path.rglob("*.h5"):
        try:
            rel_fname = fname.relative_to(folder)
            file_name = str(rel_fname.stem) + ".h5"            
            if not file_name in files_metadata:                
                files_metadata[file_name] = {
                    "exists": True,
                    "rel_path": str(rel_fname),
                    "measurement_name":get_measurement_name(fname),
                    "dataset_names": get_dset_names(fname),
                    "processed": False,
                }
        except Exception as err:
            print("failed to process", rel_fname, err)
    for d in files_metadata.values():
        d["exists"] = (Path(folder) / d["rel_path"]).exists()

    return files_metadata


def process_metadata(
    meta_data: Dict, snippets: Dict, descriptive_snippets: Dict
) -> None:
    source = [mk_load_line(meta_data)]

    snippet = snippets.get(meta_data.get("measurement_name", ""), None)
    if snippet:
        source.append(snippet)

    for requires, snip in descriptive_snippets:
        if requires.issubset(set(meta_data.get("dataset_names", []))):
            source.append(snip)
            break

    meta_data["processed"] = True

    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": source,
    }


def mk_load_line(meta_data):
    return f'data = loaders.load_{meta_data["measurement_name"]}(r"{meta_data["rel_path"]}")\n'


def mk_cell_1_source(files_metadata) -> List[str]:
    last_file_meta = find_latest_file(files_metadata)

    rel_fnames = []
    for fname in files_metadata.values():
        if fname["exists"]:
            rel_fnames.append(f'r"{fname["rel_path"]}"')

    lines = [
        "# CELL #1: AUTOGENERATED CELL: DO NOT ALTER THIS CELL, PROGRESS MAY BE LOST. use CELL #3 onwards",
        "import numpy as np",
        "from matplotlib import pylab as plt",
        "",
        "",
        f"from h5_data_loaders import load, find_settings",
        "",
        #f'# data = load(r"{last_file_meta["rel_path"]}")',
    ] + [f"fnames=[{', '.join(rel_fnames)}]\n"]

    return lines


def mk_cell_2_source(files_metadata: Dict) -> List[str]:
    return [
        "# CELL #2 ALTERNATIVE TO CELL #1. Only addition and commenting of lines are persistant",
        "import h5_data_loaders as loaders",
    ] + [mk_load_line(v) for v in files_metadata.values() if v["exists"]]


def update_cell_2(nb_content: Dict, files_metadata: Dict) -> Dict:
    for new_line in mk_cell_2_source(files_metadata):
        skipp = False
        for old_line in nb_content["cells"][1]["source"]:
            if new_line.strip().lower() in old_line.strip().lower():
                skipp = True
                break
        if not skipp:
            nb_content["cells"][1]["source"].append(new_line)
    nb_content["cells"][1]["execution_count"] = None
    return nb_content


def update_cell_1(nb_content, files_metadata):
    nb_content["cells"][0]["source"] = mk_cell_1_source(files_metadata)
    nb_content["cells"][0]["execution_count"] = None


def update_files_metadata(nb_content, files_metadata):
    nb_content["metadata"]["files_metadata"] = files_metadata


def find_latest_file(files_metadata: Dict) -> Union[Dict, None]:
    values = list(files_metadata.values())
    index = len(values) - 1
    while index >= 0:
        if values[index]["exists"]:
            return values[index]
        index -= 1


def add_last_file_cell(
    nb_content: Dict,
    files_metadata: Dict,
    snippets: Dict,
    descriptive_snippets: Tuple,
) -> Dict:
    last_file = find_latest_file(files_metadata)
    if last_file is None:
        print("no existing data file found")
        return nb_content
    nb_content["cells"].append(
        process_metadata(last_file, snippets, descriptive_snippets)
    )
    return nb_content


def generate_ipynb(
    folder: str = ".", ipynb_fname: Union[Path, None] = None
) -> Tuple[Path, Dict]:
    if ipynb_fname is None:
        ipynb_fname = Path(folder) / IPYNB_DEMO_FNAME

    if ipynb_fname.exists():
        with open(ipynb_fname, "r") as file:
            nb_content = json.load(file)
        if not "cells" in nb_content or len(nb_content["cells"]) < 2:
            nb_content = new_empty_nb_content(2)
    else:
        nb_content = new_empty_nb_content(2)

    return ipynb_fname, nb_content


def load_snippets(snippets_fname: Union[str, None] = None) -> Tuple[Dict, Tuple]:
    if snippets_fname is None:
        return {}, ()
    with open(snippets_fname, "r") as file:
        DESCRIPTIVE_SNIPPETS, snippets = json.load(file)

    descriptive_snippets = tuple((frozenset(k), v) for k, v in DESCRIPTIVE_SNIPPETS)

    return snippets, descriptive_snippets


def update_ipynb(
    folder: str = ".",
    ipynb_fname: Union[Path, None] = None,
    snippets: Dict = {},
    descriptive_snippets: Tuple = (),
) -> Path:
    ipynb_fname, nb_content = generate_ipynb(folder, ipynb_fname)

    files_metadata = get_files_metadata(folder, nb_content)
    update_cell_1(nb_content, files_metadata)
    update_cell_2(nb_content, files_metadata)
    add_last_file_cell(nb_content, files_metadata, snippets, descriptive_snippets)
    update_files_metadata(nb_content, files_metadata)

    with open(ipynb_fname, "w") as file:
        json.dump(nb_content, file)

    return ipynb_fname


def analyze_with_ipynb(folder: str = ".", snippets={}, descriptive_snippets=()) -> None:
    loaders_fname, dset_names = generate_loaders_py(folder)
    ipynb_path = update_ipynb(
        folder, snippets=snippets, descriptive_snippets=descriptive_snippets
    )

    print("")
    print("generated", loaders_fname, f"with {len(dset_names)} loader(s)")
    print("")
    print("check", ipynb_path)
    print("")

    if ipynb_path.exists():
        open_file(ipynb_path)


if __name__ == "__main__":
    analyze_with_ipynb(".")
